name: Sync to Hugging Face Space

on:
  push:
    branches: [ main ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true  # penting untuk file besar seperti .h5 via Git LFS

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add space https://huggingface.co/spaces/farhanrenardi/Male_Pattern_Baldness.git || true
          git push --force https://farhanrenardi:$HF_TOKEN@huggingface.co/spaces/farhanrenardi/Male_Pattern_Baldness.git main